# Settings for the app
app:
  # HTML Title
  title: Newberg Transportation System Plan Update
  # Header name
  name: Newberg Transportation System Plan Update
  # Meta description that will show up in Google search results
  meta_description: _(Tell us what you think about the Transportation System in Newberg County by adding comments to the map!)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 45.302560955704294
      lng: -122.96912245976273
    zoom: 15
    minZoom: 13
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: /static/data/philadelphia.geojson
      type: json
      rules:
        - condition: 'true'
          style:
            color: "#444"
            opacity: 0.6
            fillOpacity: 0.1
            weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  pedestrian:
    label: _(Pedestrian issue)
    rules:
      - condition: '"{{location_type}}" === "pedestrian"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  bicycle:
    label: _(Bicycle issue)
    rules:
      - condition: '"{{location_type}}" === "bicycle"'
        icon:
          iconUrl: /static/css/images/markers/dot-4ab767.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-4ab767.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  transit:
    label: _(Transit issue)
    rules:
      - condition: '"{{location_type}}" === "transit"'
        icon:
          iconUrl: /static/css/images/markers/dot-e1264d.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-e1264d.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  vehicle:
    label: _(Motor vehicle issue)
    rules:
      - condition: '"{{location_type}}" === "vehicle"'
        icon:
          iconUrl: /static/css/images/markers/dot-f95016.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41] 
  freight:
    label: _(Freight issue)
    rules:
      - condition: '"{{location_type}}" === "freight"'
        icon:
          iconUrl: /static/css/images/markers/dot-70d52c.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-70d52c.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  other:
    label: _(Other issue)
    rules:
      - condition: '"{{location_type}}" === "other"'
        icon:
          iconUrl: /static/css/images/markers/dot-d849e0.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-d849e0.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a comment)
  help_text: _(What do you like or don’t like? What problems do you see with safety, congestion, accessibility, or connectivity?)
  action_text: _(commented)
  title: _(Tell us about this location)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Share my comments)
  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Location Name)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
        - key: required
    - prompt: _(What mode of transportation?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Pedestrian)
          value: pedestrian
        - label: _(Bicycle)
          value: bicycle
        - label: _(Transit)
          value: transit
        - label: _(Motor Vehicle)
          value: vehicle
        - label: _(Freight)
          value: freight
        - label: _(Other)
          value: other
      name: location_type
      attrs:
        - key: required
    - prompt: _(Tell us about this location.)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Your email (optional))
      type: text
      name: private-email
      attrs:
        - key: placeholder
          value: _(Email)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true