# Settings for the app
app:
  # HTML Title
  title: Columbia County Transportation System Plan
  # Header name
  name: Columbia County Transportation System Plan
  # Meta description that will show up in Google search results
  meta_description: _(Shareabouts is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 45.91971029962419
      lng: -123.03572309785523
    zoom: 8
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  bicycle:
    label: _(Bicycle issue)
    rules:
      - condition: '"{{location_type}}" === "bicycle"'
        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25,41]
          shadowSize: [41,41]
          iconAnchor: [12, 41]
  pedestrian:
    label: _(Pedestrian issue)
    rules:
      - condition: '"{{location_type}}" === "pedestrian"'
        icon:
          iconUrl: /static/css/images/markers/dot-31b2c4.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-31b2c4.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25,41]
          shadowSize: [41,41]
          iconAnchor: [12, 41]
  transit:
    label: _(Transit issue)
    rules:
      - condition: '"{{location_type}}" === "transit"'
        icon:
          iconUrl: /static/css/images/markers/dot-4bad92.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-4bad92.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25,41]
          shadowSize: [41,41]
          iconAnchor: [12, 41]
  vehicle:
    label: _(Vehicle issue)
    rules:
      - condition: '"{{location_type}}" === "vehicle"'
        icon:
          iconUrl: /static/css/images/markers/dot-5359d7.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-5359d7.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25,41]
          shadowSize: [41,41]
          iconAnchor: [12, 41]
  freight:
    label: _(Freight issue)
    rules:
      - condition: '"{{location_type}}" === "freight"'
        icon:
          iconUrl: /static/css/images/markers/dot-744edc.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-744edc.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25,41]
          shadowSize: [41,41]
          iconAnchor: [12, 41]
  other:
    label: _(Other issue)
    rules:
      - condition: '"{{location_type}}" === "other"'
        icon:
          iconUrl: /static/css/images/markers/dot-fa307d.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-fa307d.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25,41]
          shadowSize: [41,41]
          iconAnchor: [12, 41]

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000


place:
  adding_supported: true
  add_button_label: _(Identify an issue)
  action_text: _(identified)
  title: _(Describe the issue)
  action_text: _(identified)
  anonymous_name: _(Someone)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Show As List)
  show_map_button_label: _(Show On Map)
  submit_button_label: _(Submit)
  items:
    - prompt: _(Your Name (optional))
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Choose an issue type)
      name: location_type
      type: select
      options:
        - label: _(Choose...)
          value: no-choice
        - label: _(Pedestrian)
          value: pedestrian
        - label: _(Bicycle)
          value: bicycle
        - label: _(Transit)
          value: transit
        - label: _(Motor vehicle)
          value: vehicle
        - label: _(Freight)
          value: freight
        - label: _(Other)
          value: other
    - prompt: _(Describe the location)
      type: text
      name: name
      attrs:
        - key: size
          value: 30
    - prompt: _(Tell us what you like or don't like)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(e.g. safety, congestion, accessibility, connectivity of locations)

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name


support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  response_name: _(support)
  response_plural_name: _(supports)
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true